# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "mmarkwort-build-pipeline" ]
  pull_request:
    branches: [ "main", "mmarkwort-build-pipeline" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Apply version
      run: |
           export PATH="$PATH:/root/.dotnet/tools:/gitversion"
           dotnet tool install --global GitVersion.Tool --version 5.12.0
           dotnet-gitversion /updateprojectfiles
           export SEMVER=`dotnet-gitversion -showvariable SemVer`
           echo "SEMVER=$SEMVER"
    - name: Restore dependencies
      run: dotnet restore src/MSDMarkwort.Kicad.sln
    - name: Build
      run: dotnet build src/MSDMarkwort.Kicad.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MSDMarkwort.Kicad.sln --configuration Release --no-build --verbosity normal
